//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Appointment = new HashSet<Appointment>();
            this.Reception = new HashSet<Reception>();
            this.Vaccination = new HashSet<Vaccination>();
            this.VisitHistory = new HashSet<VisitHistory>();
        }
    
        public int IdAnimal { get; set; }
        public int IdOwner { get; set; }
        public int IdType { get; set; }
        public string Name { get; set; }
        public double Age { get; set; }
        public string Breed { get; set; }
        public string Color { get; set; }
        public string info { get { return IdAnimal + " " + Name; } }


        public Nullable<int> IdCategoryAnimal { get; set; }
    
        public virtual CategoryAnimal CategoryAnimal { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual TypeAnimal TypeAnimal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reception> Reception { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vaccination> Vaccination { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitHistory> VisitHistory { get; set; }
    }
}
