//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appointment()
        {
            this.MedicineAppointment = new HashSet<MedicineAppointment>();
            this.VisitHistory = new HashSet<VisitHistory>();
        }
    
        public int IdAppointment { get; set; }
        public int IdUser { get; set; }
        public int IdAnimal { get; set; }
        public string Appointment1 { get; set; }
        public System.DateTime DateAppointment { get; set; }
        public Nullable<System.DateTime> DateRepeatReception { get; set; }
        public Nullable<bool> Finish { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicineAppointment> MedicineAppointment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitHistory> VisitHistory { get; set; }
    }
}
