//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineAppointment
    {
        public int IdMedicineAppointment { get; set; }
        public int IdMedicine { get; set; }
        public int IdAppointment { get; set; }
        public Nullable<double> Dose { get; set; }
    
        public virtual Appointment Appointment { get; set; }
        public virtual Medicine Medicine { get; set; }
    }
}
