//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicIS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicEntities : DbContext
    {
        public ClinicEntities()
            : base("name=ClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Appointment> Appointment { get; set; }
        public virtual DbSet<CategoryAnimal> CategoryAnimal { get; set; }
        public virtual DbSet<GroupMedicine> GroupMedicine { get; set; }
        public virtual DbSet<Medicine> Medicine { get; set; }
        public virtual DbSet<MedicineAppointment> MedicineAppointment { get; set; }
        public virtual DbSet<Owner> Owner { get; set; }
        public virtual DbSet<Reception> Reception { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceReception> ServiceReception { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeAnimal> TypeAnimal { get; set; }
        public virtual DbSet<TypeGender> TypeGender { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Vaccination> Vaccination { get; set; }
        public virtual DbSet<VisitHistory> VisitHistory { get; set; }
    }
}
