//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reception
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reception()
        {
            this.VisitHistory = new HashSet<VisitHistory>();
        }
    
        public int IdReception { get; set; }
        public int IdUser { get; set; }
        public int IdAnimal { get; set; }
        public System.DateTime DateReception { get; set; }
        public System.TimeSpan TimeReception { get; set; }
        public string Anamnesis { get; set; }
        public string Diagnoses { get; set; }
        public int IdService { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VisitHistory> VisitHistory { get; set; }
    }
}
