//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceReception
    {
        public int IdServiceReception { get; set; }
        public int IdService { get; set; }
        public int IdReception { get; set; }
    
        public virtual Reception Reception { get; set; }
        public virtual Service Service { get; set; }
    }
}
