//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccination
    {
        public int IdVaccination { get; set; }
        public int IdAnimal { get; set; }
        public int IdUser { get; set; }
        public System.DateTime DateVaccination { get; set; }
        public int IdMedicine { get; set; }
        public System.DateTime DateRepeatVaccination { get; set; }
        public Nullable<bool> Finish { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Medicine Medicine { get; set; }
        public virtual User User { get; set; }
    }
}
