//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicIS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VisitHistory
    {
        public int IdVisitHistory { get; set; }
        public int IdAnimal { get; set; }
        public int IdAppointment { get; set; }
        public int IdReception { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Appointment Appointment { get; set; }
        public virtual Reception Reception { get; set; }
    }
}
